# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ska < Formula
  desc "SKA is a CLI and Library to scaffold, maintain and update from upstream blueprint your projects."
  homepage "https://github.com/gchiesa/ska"
  version "0.0.7"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/gchiesa/ska/releases/download/v0.0.7/ska_0.0.7_darwin_amd64.tar.gz"
      sha256 "45375838134ae8b35061b2670977acb46f474b17b4ef39da1b02682f9afa4c92"

      def install
        bin.install "ska"
      end
    end
    on_arm do
      url "https://github.com/gchiesa/ska/releases/download/v0.0.7/ska_0.0.7_darwin_arm64.tar.gz"
      sha256 "4aefd9e7f7b30070c3f3534977a76ed324995ee1273313042f925395d47175d4"

      def install
        bin.install "ska"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gchiesa/ska/releases/download/v0.0.7/ska_0.0.7_linux_amd64.tar.gz"
        sha256 "1d493d77ddface9da29dc92c9493d8550b57f075716b62076528c3e7cc5a9a3d"

        def install
          bin.install "ska"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/gchiesa/ska/releases/download/v0.0.7/ska_0.0.7_linux_armv6.tar.gz"
        sha256 "124313c29d9b820279d884bda927c3fde97c72c2e0f09e162a81bdb6cb946e95"

        def install
          bin.install "ska"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/gchiesa/ska/releases/download/v0.0.7/ska_0.0.7_linux_arm64.tar.gz"
        sha256 "d0140bb788ecfa6bb2acd2174ea2130cc22cc619df6dcd8f9eacf32049d6cee4"

        def install
          bin.install "ska"
        end
      end
    end
  end
end
